name: cv-facades
channels: [pytorch, conda-forge, defaults]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - opencv
  - matplotlib
  - tqdm
  - pyyaml
  - scikit-learn
  - pip
  - pip:
      - python-osc
